openapi: 3.0.3
info:
  title: test
  version: 1.0.0
paths:
  /test/:
    get:
      operationId: doSomething
      parameters:
        - name: test
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/SomeTypeContainingANullableMap"
      responses:
        200:
          description: OK
components:
  schemas:
    SomeTypeContainingANullableMap:
      type: object
      properties:
        aMap:
          $ref: "#/components/schemas/MapValue"
    MapValue:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/MappedType"
      nullable: true
    MappedType:
      type: object
      properties:
        someProperty:
          type: string
          nullable: true
